- name: Setup Environment
  hosts: localhost
  become: yes
  vars_files:
    - ../config/packages.yml
    - ../config/config.yml

  tasks:
    # 下載並安裝 Miniconda
    - name: Download and install miniconda in all containers
      shell: |
        docker exec {{ item }} bash -c "
          cd /home && \
          wget {{ miniconda_url }} && \
          chmod +x {{ miniconda_installer }} && \
          bash {{ miniconda_installer }} -b && \
          rm {{ miniconda_installer }} && \
          echo 'export PATH=/root/miniconda3/bin:$PATH' >> /root/.bashrc && \
          source /root/.bashrc"
      loop: "{{ nodes }}"

    # 建立虛擬環境
    - name: Create Conda Environment
      shell: |
        docker exec {{ item }} bash -c "
          export PATH=/root/miniconda3/bin:$PATH && \
          conda install -y -c conda-forge {{ python_packages | join(' ') }}"
      loop: "{{ nodes }}"



    # 建立虛擬環境
    - name: Create Conda Environment
      shell: |
        docker exec {{ item }} bash -c "
          export PATH=/root/miniconda3/bin:$PATH && \
          conda create --name {{ environment_name }} python={{ python_version }} -y"
      loop: "{{ nodes }}"

    # 安裝 python 套件
    - name: Activate Conda Environment and Install Python Packages
      shell: |
        docker exec {{ item }} bash -c "
          export PATH=/root/miniconda3/bin:$PATH && \
          conda init {{ environment_name }} && \
          conda activate {{ environment_name }} && \
          conda install -y -c conda-forge {{ python_packages | join(' ') }}"
      loop: "{{ nodes }}"

